In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.random.randint(1,100,15)
a


array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [4]:
b = np.random.randint(1,200,24).reshape(6,4)
b

array([[ 37, 101,  24,  81],
       [149, 143,   1, 169],
       [183, 198, 173,  10],
       [ 57,  12, 108, 141],
       [174, 154,  76, 108],
       [109, 183, 197,  21]], dtype=int32)

In [5]:
np.sort(a)[::-1]

array([91, 85, 76, 59, 57, 54, 51, 48, 34, 28, 15, 15, 15,  1,  1],
      dtype=int32)

In [6]:
np.sort(b,axis=0)

array([[ 37,  12,   1,  10],
       [ 57, 101,  24,  21],
       [109, 143,  76,  81],
       [149, 154, 108, 108],
       [174, 183, 173, 141],
       [183, 198, 197, 169]], dtype=int32)

In [7]:
np.append(a,200)

array([ 15,  15,  57,  28,  48,  85,  91,   1,  51,  15,  34,   1,  59,
        54,  76, 200])

In [8]:
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[3.70000000e+01, 1.01000000e+02, 2.40000000e+01, 8.10000000e+01,
        2.59200265e-01],
       [1.49000000e+02, 1.43000000e+02, 1.00000000e+00, 1.69000000e+02,
        1.62635576e-01],
       [1.83000000e+02, 1.98000000e+02, 1.73000000e+02, 1.00000000e+01,
        4.70185603e-01],
       [5.70000000e+01, 1.20000000e+01, 1.08000000e+02, 1.41000000e+02,
        3.41082836e-01],
       [1.74000000e+02, 1.54000000e+02, 7.60000000e+01, 1.08000000e+02,
        3.04737999e-01],
       [1.09000000e+02, 1.83000000e+02, 1.97000000e+02, 2.10000000e+01,
        6.23020954e-01]])

In [9]:
# np concatenate
c= np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis = 1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [11]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
# np.unique
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [13]:
# # np.expand
np.expand_dims(a,axis = 0)
np.expand_dims(a,axis = 1)


array([[15],
       [15],
       [57],
       [28],
       [48],
       [85],
       [91],
       [ 1],
       [51],
       [15],
       [34],
       [ 1],
       [59],
       [54],
       [76]], dtype=int32)

In [14]:
# np.where
a 

array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [15]:
np.where(a>50)

(array([ 2,  5,  6,  8, 12, 13, 14]),)

In [16]:
# np.where(condition,true,false)
np.where(a>50,0,a)

array([15, 15,  0, 28, 48,  0,  0,  1,  0, 15, 34,  1,  0,  0,  0],
      dtype=int32)

In [17]:
np.where(a%2 == 0,0,a)

array([15, 15, 57,  0,  0, 85, 91,  1, 51, 15,  0,  1, 59,  0,  0],
      dtype=int32)

In [18]:
# np.cumsum
a

array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [19]:
np.cumsum(a)

array([ 15,  30,  87, 115, 163, 248, 339, 340, 391, 406, 440, 441, 500,
       554, 630])

In [20]:
b 

array([[ 37, 101,  24,  81],
       [149, 143,   1, 169],
       [183, 198, 173,  10],
       [ 57,  12, 108, 141],
       [174, 154,  76, 108],
       [109, 183, 197,  21]], dtype=int32)

In [21]:
np.cumsum(b)

array([  37,  138,  162,  243,  392,  535,  536,  705,  888, 1086, 1259,
       1269, 1326, 1338, 1446, 1587, 1761, 1915, 1991, 2099, 2208, 2391,
       2588, 2609])

In [22]:
np.cumsum(b,axis = 0)

array([[ 37, 101,  24,  81],
       [186, 244,  25, 250],
       [369, 442, 198, 260],
       [426, 454, 306, 401],
       [600, 608, 382, 509],
       [709, 791, 579, 530]])

In [23]:
np.cumsum(b,axis = 1)

array([[ 37, 138, 162, 243],
       [149, 292, 293, 462],
       [183, 381, 554, 564],
       [ 57,  69, 177, 318],
       [174, 328, 404, 512],
       [109, 292, 489, 510]])

In [24]:
# np.cumprod

np.cumprod(a)

array([                  15,                  225,                12825,
                     359100,             17236800,           1465128000,
               133326648000,         133326648000,        6799659048000,
            101994885720000,     3467826114480000,     3467826114480000,
         204601740754320000, -7398250072976271616, -8864683334910094336])

In [25]:
a

array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [26]:
# np.percentile
np.percentile(a,100)

np.float64(91.0)

In [27]:
np.percentile(a,0)

np.float64(1.0)

In [28]:
np.percentile(a,50)

np.float64(48.0)

In [29]:
# np.histogram
a

array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [30]:
np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([2, 3, 1, 1, 1, 4, 0, 1, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [31]:
# np.corrcoef

In [32]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [33]:
#np.isin
a

array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [34]:
items = [10,20,30,40,50,60,70,80,90]
a[np.isin(a,items)]


array([], dtype=int32)

In [35]:
# np.flip
a

array([15, 15, 57, 28, 48, 85, 91,  1, 51, 15, 34,  1, 59, 54, 76],
      dtype=int32)

In [36]:
np.flip(a)

array([76, 54, 59,  1, 34, 15, 51,  1, 91, 85, 48, 28, 57, 15, 15],
      dtype=int32)

In [37]:
b

array([[ 37, 101,  24,  81],
       [149, 143,   1, 169],
       [183, 198, 173,  10],
       [ 57,  12, 108, 141],
       [174, 154,  76, 108],
       [109, 183, 197,  21]], dtype=int32)

In [38]:
np.flip(b,axis = 1)

array([[ 81,  24, 101,  37],
       [169,   1, 143, 149],
       [ 10, 173, 198, 183],
       [141, 108,  12,  57],
       [108,  76, 154, 174],
       [ 21, 197, 183, 109]], dtype=int32)

# set functions


In [39]:
# np.union1d
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7,8])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.intersect1d(m,n)

array([3, 4, 5])

In [41]:
np.setdiff1d(m,n)

array([1, 2])

In [42]:
np.setxor1d(m,n)

array([1, 2, 6, 7, 8])

In [44]:
np.in1d(n,1)

AttributeError: module 'numpy' has no attribute 'in1d'