In [1]:
import numpy as ln

# Create a 2D array (5×5) #

In [7]:
a = [3,5,4,22,55,6,7,8,5,34,65,67,55,66,345,34,0,4,45,45,56,67,56,32,56]
aar = ln.array(a)
s = aar.reshape(5,5)
print(s)

[[  3   5   4  22  55]
 [  6   7   8   5  34]
 [ 65  67  55  66 345]
 [ 34   0   4  45  45]
 [ 56  67  56  32  56]]


## Extract second row and third column ##

In [8]:
print(s[1])
print(s[2])

[ 6  7  8  5 34]
[ 65  67  55  66 345]


##  Find row-wise mean (axis=1)

In [10]:
d = s.mean(axis = 1)
print(d)

[ 17.8  12.  119.6  25.6  53.4]


# Find column-wise sum (axis=0)

In [14]:
e = s.sum(axis = 0)
print(e)

[164 146 127 170 535]


 ## Filter elements greater than 50 #

In [17]:
g = s [s > 50]
print(g)

[ 55  65  67  55  66 345  56  67  56  56]


## Replace values less than 20 with 0 #

In [19]:
s[ s < 20] = 0
print(s)

[[  0   0   0  22  55]
 [  0   0   0   0  34]
 [ 65  67  55  66 345]
 [ 34   0   0  45  45]
 [ 56  67  56  32  56]]


In [28]:
l = s.ravel()
print(l)


[  0   0   0  22  55   0   0   0   0  34  65  67  55  66 345  34   0   0
  45  45  56  67  56  32  56]


In [35]:
l = ln.sort(s,axis = None)
print(l[::-1])

[345  67  67  66  65  56  56  56  55  55  45  45  34  34  32  22   0   0
   0   0   0   0   0   0   0]


#  Find index of maximum value

In [37]:
print(l.max())


345


## Flatten a 2D array

In [38]:
flt = s.ravel()
print(flt)

[  0   0   0  22  55   0   0   0   0  34  65  67  55  66 345  34   0   0
  45  45  56  67  56  32  56]


## Reshape a 1D array into (4×5)

In [40]:
d =[3.4,353,67,232,5,34,45,22,54,2,24,34,66,678,67,45,45,66,76,56]
q = ln.array(d)
o = q.reshape(4,5)
print(o)

[[  3.4 353.   67.  232.    5. ]
 [ 34.   45.   22.   54.    2. ]
 [ 24.   34.   66.  678.   67. ]
 [ 45.   45.   66.   76.   56. ]]
