## Numpy Array vs Python lists

In [31]:
# speed 
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c=[]
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

3.5480473041534424


In [32]:
# numpy 
import numpy as np
a = np.arange(10000000)
b= np.arange(10000000,20000000)
start = time.time()
c = a + b
print(time.time()-start)

0.2748148441314697


In [33]:
7.73/0.10


77.3

In [34]:
# memory
a = [i for i in range (10000000)]
import sys
sys.getsizeof(a)

89095160

In [35]:
a = np.arange(10000000,dtype=np.int16)
sys.getsizeof(a)

20000112

In [36]:
# convience



# Advanced Indexing

In [37]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
a[1,2]

np.int64(6)

In [39]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [40]:
# Fancing indexing 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [42]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

## Boolean Indexing

In [43]:
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[45, 17, 19, 33],
       [12, 32, 93, 36],
       [54, 67, 35, 25],
       [83, 44, 15, 62],
       [93, 66, 19, 21],
       [81, 12, 99,  2]], dtype=int32)

In [44]:
# find all numbers to greater than 50
a[a > 50]

array([93, 54, 67, 83, 62, 93, 66, 81, 99], dtype=int32)

In [45]:
# find all number greater than 50 and are even
a[(a > 50) & (a % 2 == 0)]

array([54, 62, 66], dtype=int32)

## BroadCasting

In [ ]:
# Same Shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)
c = a+b
print(c)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Diff. Shape

a = np.arange(6).reshape(2,3)
b = np.arange(6,9).reshape(1,3)
print(a)
print(b)
c = a+b
print(c)

[[0 1 2]
 [3 4 5]]
[[6 7 8]]
[[ 6  8 10]
 [ 9 11 13]]


# Mathematical formulas

In [52]:
#sigmoid
def sigmoid(array):
    return 1/(1 + np.exp(-array))

a= np.arange(10)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [60]:
# mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)



In [61]:
def mef(actual,predicted):
    return np.mean(actual - predicted) **2

mef(actual,predicted)

np.float64(16.0)

In [54]:
actual

array([39,  2,  5,  6, 46, 20, 25,  3, 43, 32,  2,  1, 30, 48, 41,  5, 23,
       46, 25, 29, 45,  5, 30,  7, 32], dtype=int32)

In [55]:
predicted

array([31, 38,  3, 40, 40,  1, 44,  5,  8, 31,  7, 17, 49, 19, 29, 21, 16,
       44, 34, 29, 39, 25,  7,  1, 35], dtype=int32)

In [ ]:
# binary cross entropy